### ISSUE TITLE
Change the sizing of the middle news box

### ISSUE THREAD

**Issue by abhishekgit03** [abhishekgit03/NewsApp#1]
The size of the middle box changes according to the news image. Change to code the so that the box dimensions same even when the image size changes.

**Comment by harsh0620** [comment]
Hi @abhishekgit03 Please assign me this task.

**Comment by abhishekgit03** [comment]
Go ahead!

**Comment by harsh0620** [comment]
Task submitted and merged.
Do not forget to close this issue.
