### ISSUE TITLE
[Bug] The News category buttons does not stay selected.

### ISSUE THREAD

**Issue by abhishekgit03** [abhishekgit03/NewsApp#2]
- The News category buttons must have blue color to show that the particular category is selected by users. 
- The button color doesnt stay blue when users swipe through the news.

**Comment by harsh0620** [comment]
Hi @abhishekgit03 Please assign me this task.

**Comment by abhishekgit03** [comment]
@harsh0620 Go ahead! I have assigned you.

**Comment by harsh0620** [comment]
Task submitted and merged.
Do not forget to close this issue.
