### ISSUE TITLE
[Modify]Hover button Effect

### ISSUE THREAD

**Issue by abhishekgit03** [abhishekgit03/NewsApp#4]
- Add some hover effects to the category boxes such as "General", "Entertainment" etc when clicked by the user 
- Change the border styling of these boxes

**Comment by Dorcastunmise** [comment]
Hello @abhishekgit03 , I'll like to work on this

**Comment by abhishekgit03** [comment]
@Dorcastunmise Go ahead!

**Comment by abhishekgit03** [comment]
@Dorcastunmise I saw your PR. I would like to say that please apply a single effect on all the four boxes. You can just add a border shadow when a user hovers upon the boxes.
Steps:

- Pull the repo again.
- Make the required changes.
- Push your changes to the same PR again.

**Comment by Dorcastunmise** [comment]
This is stressful. But I'll do it.

**Comment by Dorcastunmise** [comment]
Hello @abhishekgit03 , are you satisfied with my latest PR? Please let me know.
